### ISSUE TITLE
Possible typo in the `networking_and_internals` document

### ISSUE THREAD

**Issue by bdshroyer** [rabbitmq/internals#13]
Under the "Messaging and Protocol Listeners" section, we see the line:

"`rabbit_networking:boot_tcp/0` and `rabbit_networking:boot_tcp/0` start plain TCP and TLS listeners, respectively."

I don't think `boot_tcp` is supposed to be referenced twice there. The `rabbit_networking` module in rabbitmq-common has `boot_tcp` method and `boot_ssl` methods; I think that `boot_ssl` is the other one that needs to be referenced.

**Comment by michaelklishin** [comment]
@bdshroyer your understanding is correct.
